"""
Django settings for cubelessmail project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv


def _env_bool(name, default=False):
    """Parse a boolean environment variable with a safe fallback."""
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name, default=None):
    """Parse a comma-separated environment variable into a list of strings."""
    value = os.getenv(name, '')
    if not value.strip():
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]

# Load environment variables from .env file
load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DJANGO_ENV = os.getenv('DJANGO_ENV', 'local').strip().lower()
IS_PRODUCTION = DJANGO_ENV == 'production'
AXES_ENABLED = _env_bool('AXES_ENABLED', default=IS_PRODUCTION)
ADMIN_IP_ALLOWLIST_ENABLED = _env_bool('ADMIN_IP_ALLOWLIST_ENABLED', default=IS_PRODUCTION)
ADMIN_IP_ALLOWLIST = _env_list('ADMIN_IP_ALLOWLIST', default=[])
ADMIN_IP_ALLOWLIST_TRUST_X_FORWARDED_FOR = _env_bool(
    'ADMIN_IP_ALLOWLIST_TRUST_X_FORWARDED_FOR',
    default=False,
)

if ADMIN_IP_ALLOWLIST_ENABLED and not ADMIN_IP_ALLOWLIST:
    raise ValueError(
        'ADMIN_IP_ALLOWLIST_ENABLED is true but ADMIN_IP_ALLOWLIST is not set.'
    )

# SECURITY WARNING: keep the secret key used in production secret!
LOCAL_DEV_SECRET_KEY = 'django-insecure-local-dev-key-change-me'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', LOCAL_DEV_SECRET_KEY)
if IS_PRODUCTION and (
    not SECRET_KEY
    or SECRET_KEY == LOCAL_DEV_SECRET_KEY
    or SECRET_KEY.startswith('django-insecure-')
):
    raise ValueError(
        'Production requires a strong DJANGO_SECRET_KEY set via environment variable.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', default=not IS_PRODUCTION)

ALLOWED_HOSTS = _env_list(
    'ALLOWED_HOSTS',
    default=['localhost', '127.0.0.1'] if not IS_PRODUCTION else [],
)
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ValueError('Production requires ALLOWED_HOSTS to be set.')

CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mail',
]

if AXES_ENABLED:
    INSTALLED_APPS.append('axes')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'cubelessmail.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if ADMIN_IP_ALLOWLIST_ENABLED:
    security_middleware = 'django.middleware.security.SecurityMiddleware'
    allowlist_middleware = 'cubelessmail.middleware.AdminIPAllowlistMiddleware'
    security_index = MIDDLEWARE.index(security_middleware)
    MIDDLEWARE.insert(security_index + 1, allowlist_middleware)

if AXES_ENABLED:
    auth_middleware = 'django.contrib.auth.middleware.AuthenticationMiddleware'
    axes_middleware = 'axes.middleware.AxesMiddleware'
    auth_index = MIDDLEWARE.index(auth_middleware)
    MIDDLEWARE.insert(auth_index + 1, axes_middleware)

ROOT_URLCONF = 'cubelessmail.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cubelessmail.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

if AXES_ENABLED:
    AUTHENTICATION_BACKENDS.insert(0, 'axes.backends.AxesStandaloneBackend')

AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = timedelta(minutes=int(os.getenv('AXES_COOLOFF_MINUTES', '30')))
AXES_RESET_ON_SUCCESS = _env_bool('AXES_RESET_ON_SUCCESS', default=True)


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Environment-aware security settings:
# - Local defaults avoid breaking HTTP development.
# - Production defaults enforce HTTPS and secure cookies.
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', default=IS_PRODUCTION)
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', default=IS_PRODUCTION)
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')

SECURE_HSTS_SECONDS = int(
    os.getenv('SECURE_HSTS_SECONDS', '31536000' if IS_PRODUCTION else '0')
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=IS_PRODUCTION,
)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', default=False)
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool('SECURE_CONTENT_TYPE_NOSNIFF', default=True)
SECURE_REFERRER_POLICY = os.getenv(
    'SECURE_REFERRER_POLICY',
    'strict-origin-when-cross-origin',
)
SECURE_CROSS_ORIGIN_OPENER_POLICY = os.getenv(
    'SECURE_CROSS_ORIGIN_OPENER_POLICY',
    'same-origin',
)
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

if _env_bool('TRUST_PROXY_SSL_HEADER', default=False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Email credential encryption
# Generate a key with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
MAIL_ENCRYPTION_KEY = os.getenv('MAIL_ENCRYPTION_KEY', '')
