# Generated by Django 6.0.3 on 2026-04-12 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.emailaccount')),
            ],
            options={
                'verbose_name': 'Cached Folder',
                'verbose_name_plural': 'Cached Folders',
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CachedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('size', models.IntegerField(default=0)),
                ('flags', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.emailaccount')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.folder')),
            ],
            options={
                'verbose_name': 'Cached Message',
                'verbose_name_plural': 'Cached Messages',
                'indexes': [models.Index(fields=['account', 'folder', 'last_updated'], name='mail_cached_account_97edaf_idx'), models.Index(fields=['account', 'folder', 'uid'], name='mail_cached_account_6d5c9e_idx')],
                'unique_together': {('account', 'folder', 'uid')},
            },
        ),
    ]
