# Generated by Django 6.0.3 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_folder_cachedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmessage',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
