# Generated by Django 6.0.3 on 2026-04-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_cachedmessage_has_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='imap_password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='imap_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
