# Generated by Django 6.0.4 on 2026-04-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_encrypt_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='imap_password',
        ),
    ]
