# Generated by Django 6.0.4 on 2026-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_remove_emailaccount_imap_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='smtp_password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='smtp_port',
            field=models.IntegerField(blank=True, default=587),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
